"""Generate the executive Word document justifying a dedicated PG/PD sales resource for TIME.
US inventory, Jan 2025 - Jun 2026. June 2026 excluded from revenue/eCPM (mis-booked CPD->CPM).
No named advertisers. Charts embedded from PNGs generated by make_charts.py.
"""
import os
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

HERE = os.path.dirname(os.path.abspath(__file__))
TEAL   = RGBColor(0x0F,0x7D,0x88)
TEAL_D = RGBColor(0x0B,0x5C,0x65)
INK    = RGBColor(0x1F,0x2A,0x30)
MUTED  = RGBColor(0x5B,0x6B,0x73)
GOLD   = RGBColor(0xB8,0x86,0x1f)
GREEN  = RGBColor(0x1f,0x7A,0x52)
WHITE  = RGBColor(0xFF,0xFF,0xFF)

doc = Document()

# ---------- base styles ----------
normal = doc.styles["Normal"]
normal.font.name = "Calibri"; normal.font.size = Pt(11); normal.font.color.rgb = INK
normal.paragraph_format.space_after = Pt(6); normal.paragraph_format.line_spacing = 1.12

def shade(cell, hexcolor):
    tcPr = cell._tc.get_or_add_tcPr()
    sh = OxmlElement("w:shd"); sh.set(qn("w:val"),"clear"); sh.set(qn("w:fill"),hexcolor)
    tcPr.append(sh)

def set_cell_text(cell, text, bold=False, color=None, size=10, align="left", fill=None):
    cell.text = ""
    p = cell.paragraphs[0]
    p.alignment = {"left":WD_ALIGN_PARAGRAPH.LEFT,"center":WD_ALIGN_PARAGRAPH.CENTER,
                   "right":WD_ALIGN_PARAGRAPH.RIGHT}[align]
    r = p.add_run(text); r.bold = bold; r.font.size = Pt(size)
    if color is not None: r.font.color.rgb = color
    if fill: shade(cell, fill)
    p.paragraph_format.space_after = Pt(2); p.paragraph_format.space_before = Pt(2)

def H(text, level=1, color=TEAL_D, size=None, space_before=14):
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(space_before); p.paragraph_format.space_after = Pt(4)
    r = p.add_run(text); r.bold = True
    r.font.color.rgb = color
    r.font.size = Pt(size if size else (16 if level==1 else 13))
    return p

def body(text, size=11, italic=False, color=INK, after=6, bold=False):
    p = doc.add_paragraph()
    r = p.add_run(text); r.italic = italic; r.bold = bold
    r.font.size = Pt(size); r.font.color.rgb = color
    p.paragraph_format.space_after = Pt(after)
    return p

def bullet(text, bold_lead=None):
    p = doc.add_paragraph(style="List Bullet")
    if bold_lead:
        r = p.add_run(bold_lead+" "); r.bold = True; r.font.color.rgb = TEAL_D; r.font.size=Pt(11)
    r2 = p.add_run(text); r2.font.size = Pt(11); r2.font.color.rgb = INK
    p.paragraph_format.space_after = Pt(3)
    return p

def callout(text_bold, text_rest):
    """Single-cell shaded callout box with teal left accent feel."""
    t = doc.add_table(rows=1, cols=1); t.alignment = WD_TABLE_ALIGNMENT.CENTER
    c = t.cell(0,0); shade(c, "E8F4F5")
    c.text = ""
    p = c.paragraphs[0]; p.paragraph_format.space_before=Pt(6); p.paragraph_format.space_after=Pt(6)
    if text_bold:
        rb = p.add_run(text_bold+"  "); rb.bold=True; rb.font.color.rgb=TEAL_D; rb.font.size=Pt(11.5)
    rr = p.add_run(text_rest); rr.font.size=Pt(11); rr.font.color.rgb=INK
    # thin border
    set_table_borders(t, "0F7D88", 12)
    doc.add_paragraph().paragraph_format.space_after = Pt(2)
    return t

def set_table_borders(table, color="C9D2D4", sz=6):
    tbl = table._tbl; tblPr = tbl.tblPr
    borders = OxmlElement("w:tblBorders")
    for edge in ("top","left","bottom","right","insideH","insideV"):
        e = OxmlElement(f"w:{edge}")
        e.set(qn("w:val"),"single"); e.set(qn("w:sz"),str(sz))
        e.set(qn("w:space"),"0"); e.set(qn("w:color"),color)
        borders.append(e)
    tblPr.append(borders)

def add_image(name, width=6.4, caption=None):
    doc.add_picture(os.path.join(HERE,name), width=Inches(width))
    doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER
    if caption:
        p = doc.add_paragraph(); p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r = p.add_run(caption); r.italic=True; r.font.size=Pt(9); r.font.color.rgb=MUTED
        p.paragraph_format.space_after = Pt(8)

def table(headers, rows, widths=None, highlight_rows=None, right_from=1):
    highlight_rows = highlight_rows or []
    t = doc.add_table(rows=1, cols=len(headers)); t.alignment = WD_TABLE_ALIGNMENT.CENTER
    set_table_borders(t)
    for j,h in enumerate(headers):
        set_cell_text(t.rows[0].cells[j], h, bold=True, color=WHITE, size=9.5,
                      align="left" if j==0 else "right", fill="0B5C65")
    for i,row in enumerate(rows):
        cells = t.add_row().cells
        fill = "E8F4F5" if i in highlight_rows else ("F7FAFA" if i%2 else None)
        for j,val in enumerate(row):
            set_cell_text(cells[j], val, bold=(i in highlight_rows) or j==0 and False,
                          size=9.5, align="left" if j<right_from else "right", fill=fill)
    if widths:
        for j,w in enumerate(widths):
            for r in t.rows: r.cells[j].width = Inches(w)
    doc.add_paragraph().paragraph_format.space_after = Pt(2)
    return t

# =================================================================== TITLE
tp = doc.add_paragraph(); tp.paragraph_format.space_before = Pt(30)
r = tp.add_run("DATABEAT"); r.bold=True; r.font.size=Pt(20); r.font.color.rgb=TEAL_D
r2 = tp.add_run("  |  Prepared for TIME"); r2.font.size=Pt(12); r2.font.color.rgb=MUTED

t1 = doc.add_paragraph(); t1.paragraph_format.space_before = Pt(60)
r = t1.add_run("Scaling Programmatic Guaranteed & Preferred Deals")
r.bold=True; r.font.size=Pt(28); r.font.color.rgb=TEAL_D
t2 = doc.add_paragraph()
r = t2.add_run("The Case for a Dedicated PG/PD Sales Resource")
r.bold=True; r.font.size=Pt(18); r.font.color.rgb=TEAL
st = doc.add_paragraph(); st.paragraph_format.space_before = Pt(24)
r = st.add_run("An analysis of TIME's U.S. non-direct inventory and the incremental revenue available by "
               "converting under-priced programmatic impressions into deal-based demand.")
r.font.size=Pt(12.5); r.font.color.rgb=INK; r.italic=True

meta = doc.add_paragraph(); meta.paragraph_format.space_before = Pt(50)
for line,bold in [("Scope: U.S. inventory only",True),
                  ("Data source: Google Ad Manager, Jan 2025 – Jun 2026",False),
                  ("Note: June 2026 revenue/eCPM excluded (see Methodology)",False)]:
    rr = meta.add_run(line+"\n"); rr.bold=bold; rr.font.size=Pt(11); rr.font.color.rgb=MUTED

doc.add_page_break()

# =================================================================== EXEC SUMMARY
H("Executive Summary", 1)
body("TIME's U.S. programmatic inventory is systematically under-monetized. Non-direct channels "
     "(programmatic + house) account for roughly two-thirds of all ad impressions yet contribute only "
     "about 15% of ad revenue, because that inventory clears at open-auction rates near $2–$3 versus "
     "$20+ on directly-sold deals. This is not a traffic problem — the impressions already exist. "
     "It is a monetization and go-to-market gap.")
body("The mechanism to close the gap already exists inside the account and is proven: Preferred Deals "
     "clear at roughly $6 eCPM — more than double the general programmatic rate — but represent under 0.01% of "
     "impressions today. The opportunity is to package premium, high-impact ad units and take them to "
     "advertisers as Programmatic Guaranteed (PG) and Preferred Deals (PD) at negotiated rates of $8–$10.")
callout("The ask:",
        "Fund one dedicated PG/PD resource to proactively reach out to advertisers, build the deal "
        "pipeline, and run execution. On the top-6 ad units alone, a conservative 10% shift to PG/PD at "
        "$8 eCPM returns roughly $159K per year; a 20% shift at $10 returns roughly $430K — many times "
        "the fully-loaded cost of a single resource.")
# KPI mini-table
table(["Metric (U.S.)","Direct","Programmatic","House"],
      [["Share of impressions","36%","56%","9%"],
       ["Share of revenue","~84%","~15%","~0.3%"],
       ["eCPM","$20.19","$2.33","$0.30"]],
      widths=[2.6,1.3,1.5,1.2], right_from=1)
body("Figures reflect FY2025 (a complete, clean year); impression mix is consistent across the full period. "
     "See Methodology for the June 2026 exclusion.", size=9, italic=True, color=MUTED)

# =================================================================== METHODOLOGY
H("Data Scope & Methodology", 1)
bullet("all figures are for TIME's U.S. inventory only, exported from Google Ad Manager for the period "
       "January 2025 – June 2026.", bold_lead="Scope —")
bullet("Direct = Standard + Sponsorship line items. Programmatic = Ad Exchange + Price Priority "
       "(Media.net, Amazon/A9, etc.) + Preferred Deal + EBDA/Open Bidding. House = house line items.",
       bold_lead="Channel definitions —")
bullet("June 2026 has been excluded from all revenue and eCPM figures. A fixed-cost (CPD) deal was "
       "mistakenly entered as a CPM value, which materially inflated reported June revenue and eCPM. "
       "Impression counts are unaffected by this error. To stay conservative, revenue and eCPM exhibits "
       "are anchored on FY2025 — a complete, clean year — and on programmatic figures, which are "
       "independent of the June direct-side error.", bold_lead="June 2026 exclusion —")
bullet("no individual advertiser names are disclosed in this document; demand is summarized at the "
       "channel and platform level.", bold_lead="Confidentiality —")

# =================================================================== 1. OVERALL PERFORMANCE
H("1.  Overall Performance: Direct vs Programmatic vs House", 1)
body("The headline of the entire analysis is a single mismatch: the way TIME earns money and the way TIME "
     "serves impressions are almost mirror images of each other.")
add_image("c1_donuts.png", width=6.6,
          caption="Figure 1 — U.S. impression share vs. revenue share (FY2025). Direct = gold, Programmatic = green, House = red.")
body("Direct sales — where the team has genuinely improved and consistently commands $20+ eCPMs — "
     "converts about a third of impressions into ~84% of revenue. Programmatic does the opposite: it carries "
     "the majority of impressions but returns a fraction of the revenue, because it is largely sold through "
     "the open auction at remnant pricing. House inventory (~9% of impressions) is effectively unmonetized.")
table(["Channel","Revenue (FY25)","Rev share","Impressions (FY25)","Imp share","eCPM"],
      [["Direct","$5,352,299","84.5%","265.1M","35.7%","$20.19"],
       ["Programmatic","$959,994","15.2%","412.5M","55.5%","$2.33"],
       ["House","$19,902","0.3%","65.5M","8.8%","$0.30"],
       ["Total","$6,332,195","100%","743.1M","100%","$8.52"]],
      widths=[1.5,1.5,1.0,1.7,1.0,0.9], highlight_rows=[3], right_from=1)
callout("Why this matters:",
        "programmatic + house together are ~64% of U.S. impressions but ~15% of revenue. Even a small "
        "improvement in how that inventory is sold produces a large revenue effect, because the starting "
        "eCPM is so low.")

# =================================================================== 2. WHERE REVENUE COMES FROM
H("2.  Where the Programmatic Revenue Comes From", 1)
body("Within programmatic, revenue is concentrated in a handful of demand platforms — all transacting "
     "through the open auction or network backfill, none through negotiated deals. This is the demand we "
     "can re-capture at higher rates through PG/PD relationships.")
add_image("c2_ssp.png", width=6.6,
          caption="Figure 2 — Top programmatic partners by revenue (U.S., full period). Darker bars = largest partners.")
body("The same advertisers and platforms buying TIME's inventory today through the open auction at ~$2–$3 "
     "are exactly the demand a dedicated resource would convert into direct PG/PD deals at negotiated, "
     "premium rates — capturing margin TIME currently leaves on the table.")

# =================================================================== 3. AD-UNIT OPPORTUNITY
H("3.  The Ad-Unit Opportunity (Top 6 High-Impact Units)", 1)
body("Focusing on the six highest-volume, high-impact ad units, the pricing gap is stark and consistent: "
     "on the very same placement, directly-sold impressions earn roughly 6–13× what programmatic earns.")
add_image("c3_adunits.png", width=6.6,
          caption="Figure 3 — Direct vs. Programmatic eCPM on the same ad unit (FY2025, U.S.).")
table(["Ad unit","Direct eCPM","Prog. eCPM","Prog. impressions","Gap"],
      [["stickyfooter1","$22.92","$1.79","118.9M","12.8×"],
       ["leaderboard1","$18.66","$1.78","45.7M","10.5×"],
       ["inline1","$18.91","$3.25","37.1M","5.8×"],
       ["inline2","$20.76","$2.82","31.8M","7.4×"],
       ["rightrail1","$19.56","$2.88","18.9M","6.8×"],
       ["inline3","$20.05","$2.74","25.4M","7.3×"],
       ["Top-6 total","$20.42","$2.26","277.8M","9.0×"]],
      widths=[1.5,1.3,1.2,1.7,0.9], highlight_rows=[6], right_from=1)
body("These six units carry roughly 278 million programmatic impressions a year that clear at ~$2.26. That "
     "is the pool a PG/PD motion targets — not by displacing direct sales, but by pricing the non-direct "
     "inventory far closer to its true value.")

# =================================================================== 4. PROOF
H("4.  The Proof PG/PD Works Is Already in the Data", 1)
body("This is not a theoretical uplift. TIME's own account already shows that deal-based demand pays more:")
table(["Deal type","eCPM 2025","eCPM 2026","Impressions (period)","Read"],
      [["General programmatic","$2.33","$2.78","619.4M","Baseline (open auction)"],
       ["Preferred Deal (PD)","$4.50","$6.01","98,736","~2.2× baseline, tiny volume"]],
      widths=[1.9,1.1,1.1,1.6,1.9], highlight_rows=[1], right_from=1)
callout("The signal:",
        "Preferred Deals already clear at more than 2× the open-auction rate — yet they represent under "
        "0.01% of impressions. The pricing power is proven; the volume is simply untapped. A $8–$10 target "
        "is a realistic step up from a $6 rate that is already being achieved today at negligible scale.")

# =================================================================== 5. THE OPPORTUNITY
H("5.  The Opportunity: Scaling Top-6 Inventory to $8–$10 eCPM", 1)
body("Applying conservative, achievable target eCPMs of $8 and $10 to a portion of the top-6 programmatic "
     "pool (278M impressions/year at a current $2.26) yields the following incremental annual revenue:")
add_image("c4_opportunity.png", width=6.4,
          caption="Figure 4 — Incremental annual revenue by shift level and target eCPM (top-6 ad units only).")
table(["Scenario","Impressions shifted","Target eCPM","Incremental / year"],
      [["Conservative","10% (27.8M)","$8","+$159K"],
       ["Conservative","10% (27.8M)","$10","+$215K"],
       ["Base","20% (55.6M)","$8","+$319K"],
       ["Base","20% (55.6M)","$10","+$430K"],
       ["Upside","30% (83.3M)","$8","+$478K"],
       ["Upside","30% (83.3M)","$10","+$645K"]],
      widths=[1.5,2.0,1.4,1.8], highlight_rows=[3], right_from=1)
bullet("These figures cover the top-6 ad units only. The full U.S. programmatic pool is ~619M impressions, "
       "so the account-wide ceiling is materially higher.", bold_lead="Scope note —")
bullet("house inventory on these units (~14.4M impressions/yr at $1) adds a further ~$58K–$72K/yr if sold "
       "via PD at $5–$6 — near-zero-risk upside from currently unmonetized inventory.", bold_lead="Plus —")

# =================================================================== 6. THE ASK
H("6.  The Ask: A Dedicated PG/PD Sales Resource", 1)
body("Capturing this opportunity requires someone whose full-time job is to turn under-priced programmatic "
     "inventory into negotiated deals. Today no one owns this motion end-to-end, which is precisely why the "
     "gap persists despite a strong direct team.")
H("What the resource does", 2, color=TEAL, size=12, space_before=8)
bullet("proactively reach out to advertisers, agencies and DSP/SSP demand partners to build a PG/PD "
       "pipeline and bring in sales.", bold_lead="Outreach & sales —")
bullet("package premium, high-impact ad units into PG and PD offers with clear pricing, targeting and specs.",
       bold_lead="Packaging —")
bullet("set up and manage proposals and line items in GAM; run creative QA and launch readiness.",
       bold_lead="Execution —")
bullet("monitor delivery, pacing and discrepancies; deliver post-campaign reporting to drive repeat deals.",
       bold_lead="Optimization —")
H("KPIs", 2, color=TEAL, size=12, space_before=8)
table(["KPI","Target"],
      [["PG/PD deals closed / activated","monthly, growing quarter over quarter"],
       ["Proposal turnaround time","< 48 hours"],
       ["Campaign delivery rate","> 90%"],
       ["Programmatic eCPM on packaged units","$8–$10 (from ~$2.3 today)"],
       ["PG/PD share of programmatic revenue","5–10% within 3 months (from <1%)"]],
      widths=[3.6,3.0], right_from=1)
callout("Return on the resource:",
        "even the most conservative scenario (10% shift at $8 ≈ +$159K/yr, top-6 units only) covers a "
        "fully-loaded resource several times over. The base case (~$319K–$430K/yr) makes the investment "
        "decision straightforward — and it scales as the pipeline matures across the full inventory.")

# =================================================================== 7. RECOMMENDATION
H("7.  Recommendation & Next Steps", 1)
body("The opportunity is real, quantified, low-risk and additive — it does not cannibalize the direct "
     "business; it prices the inventory the direct team does not sell. We recommend proceeding.", bold=True)
bullet("approve one dedicated PG/PD sales resource to own advertiser outreach, deal-making and execution.",
       bold_lead="1.")
bullet("start with the top-6 high-impact ad units and house inventory as the initial package.",
       bold_lead="2.")
bullet("set a 90-day first-quarter goal: 3–5 live PG/PD deals, delivery >90%, and PG/PD reaching 5–10% of "
       "programmatic revenue.", bold_lead="3.")
bullet("align on go-live timing and confirm target advertiser/agency list for initial outreach.",
       bold_lead="4.")

# footer note
fp = doc.add_paragraph(); fp.paragraph_format.space_before = Pt(18)
r = fp.add_run("Prepared by Databeat for TIME  ·  U.S. inventory  ·  GAM Jan 2025 – Jun 2026 (June 2026 excluded).  "
               "All revenue/eCPM figures anchored on the clean FY2025 period and June-independent programmatic data.")
r.italic=True; r.font.size=Pt(8.5); r.font.color.rgb=MUTED

out = os.path.join(HERE,"TIME_PG-PD_Opportunity_and_Resource_Case.docx")
doc.save(out)
print("saved:", out)
